# Generated by Django 4.2.21 on 2025-08-06 11:15

import app.json_encoders
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_alter_field_user_and_product_in_recurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeAttemptLog',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_payment_id', models.CharField(blank=True, default='', help_text='Payment ID in external payment system (or payment id from shop).', max_length=128, verbose_name='External payment ID')),
                ('provider', models.CharField(blank=True, choices=[('DOLYAME', 'Dolyame'), ('SPLIT', 'Split'), ('STRIPE', 'Stripe'), ('TINKOFF', 'Tinkoff'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='', help_text='Payment provider (Tinkoff, Stripe, Dolyame, etc.).', max_length=16, verbose_name='Provider')),
                ('provider_response', models.JSONField(blank=True, encoder=app.json_encoders.AppJSONEncoder, help_text='Raw response from payment provider.', null=True, verbose_name='Provider response')),
                ('error_message', models.TextField(verbose_name='Error message')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_attempt_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Charge Attempt Error Log',
                'verbose_name_plural': 'Charge Attempt Error Logs',
                'ordering': ['-created'],
            },
        ),
    ]
